name: 'comment-changed-gradle-multi-project-action'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-15
      with:
        args: extractProjectStructure
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v18.4
    - run: |
        # make output to write comment
        COMMENT=$(node index.js ${{ steps.changed-files.outputs.all_changed_files }})
        echo "::set-output name=comment::$(echo $COMMENT)"
      id: make-output
      shell: bash
    - name: comment PR
      uses: okteto/notify-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: "${{ steps.make-output.output.comment }}"