name: 'comment-changed-gradle-multi-project-action'
description: 'Comment changed modules include indirect change by dependency.'
inputs:
  header-text:
    description: "The header message of added comment. used to identify added comment by action."
    default: Impacted Modules✨
    required: false
outputs:
  internal-modules:
    description: "internal modules"
    value: ${{ env.INTERNAL_MODULES }}
  leaf-modules:
    description: "leaf modules"
    value: ${{ env.LEAF_MODULES }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v18.4
    - run: |
        # make output to write comment
        export OUTPUT_FILE_PATH=$GITHUB_ACTION_PATH
        echo $OUTPUT_FILE_PATH 
        ./gradlew extractProjectStructure
        echo "$(node $GITHUB_ACTION_PATH/index.js ${{ steps.changed-files.outputs.all_changed_files }})" >> $GITHUB_ENV
      id: make-output
      shell: bash

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: ${{ inputs.header-text }}

    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## ${{ inputs.header-text }}
          ### Internal Modules
          ${{ env.INTERNAL_MODULES }}
          ### Leaf Modules 
          ${{ env.LEAF_MODULES }}
        reactions: eyes

    - name: Update comment
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          ## ${{ inputs.header-text }}
          ### Internal Modules
          ${{ env.INTERNAL_MODULES }}
          ### Leaf Modules 
          ${{ env.LEAF_MODULES }}
        reactions: eyes
        edit-mode: replace